name: release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
    
    - name: Restore dependencies
      run: dotnet restore src/BuilderGenerator.sln
    - name: Build
      run: dotnet build -c Release --no-restore src/BuilderGenerator.sln
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal src/BuilderGenerator.sln
    - name: Pack
      run: dotnet pack -c Release -o out -p:PackageVersion=${{ env.GitVersion_NuGetVersionV2 }} src/BuilderGenerator/BuilderGenerator.csproj
    - name: Publish
      run: dotnet nuget push ./src/BuilderGenerator/out/*.nupkg --api-key ${NUGET_APIKEY} --source https://int.nugettest.org/v3/index.json
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
